### ISSUE TITLE
关于vector

### ISSUE THREAD

**Issue by longjianjiang** [djs66256/DDComponent#3]
看了博主的源代码，发现有两个地方用到了`vector`来进行存储`NSInteger`。

之前在知乎上看到一个关于Swift的讨论，一个回答中也说到了vector：

---

这句话，我不能认同，在 iOS 开发，涉及到大量的点(CGPoint), 矩形(CGRect) 等基础对象，假如这些对象也采用引用类型，而在堆中分配，是不能忍受的。使用 Objective-C 的时候，当需要存储大量点的时候，为了性能考虑，也经常会切换到使用 C++, 用 std:vector 存储。而不是用 NSArray 将点放到 NSValue 中。

---

[ref](https://www.zhihu.com/question/47191926)

想问下，用vector将基本数据类型或者结构体不用对象的方式来存对比直接用NSArray加NSValue来包装有哪些性能上面的提升吗？

除了不占用一些堆上的内存，还有其他的吗，我是这样想的，vector内部的实现也是一个malloc的数组，所以vector内部存的元素还是放在堆上的。这里有点疑惑，麻烦博主给个解答，谢谢：）

**Comment by djs66256** [comment]
oc中的对象都是堆上的，会产生大量小内存。比如100个value，需要生成100次sizeof value，而vector是一次分配堆内存，也就是生成1次100*sizeof value。从时间性能和内存性能上100次malloc肯定比1次malloc要差。但实际上的差距在少量数据的时候并不会有太多的差别。

**Comment by longjianjiang** [comment]
了解了，谢谢博主。

**Comment by longjianjiang** [comment]
还想问一下，这个库现在有在项目在生产环境中使用吗？

**Comment by djs66256** [comment]
已经在使用，一般使用没有问题。目前在设计另一套新的方案，增加更多能力。
